Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Afghanistan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Åland Islands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Albania');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Algeria');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('American Samoa');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Andorra');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Angola');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Anguilla');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Antarctica');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Antigua and Barbuda');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Argentina');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Armenia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Aruba');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Australia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Austria');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Azerbaijan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Bahamas');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Bahrain');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Bangladesh');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Barbados');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Belarus');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Belgium');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Belize');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Benin');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Bermuda');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Bhutan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Bolivia (Plurinational State of);');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Bonaire, Sint Eustatius and Saba');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Bosnia and Herzegovina');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Botswana');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Bouvet Island');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Brazil');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('British Indian Ocean Territory');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Brunei Darussalam');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Bulgaria');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Burkina Faso');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Burundi');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Cabo Verde');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Cambodia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Cameroon');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Canada');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Cayman Islands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Central African Republic');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Chad');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Chile');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('China');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Christmas Island');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Cocos (Keeling); Islands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Colombia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Comoros');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Congo');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Congo, Democratic Republic of the');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Cook Islands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Costa Rica');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Côte dIvoire');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Croatia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Cuba');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Curaçao');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Cyprus');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Czechia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Denmark');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Djibouti');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Dominica');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Dominican Republic');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Ecuador');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Egypt');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('El Salvador');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Equatorial Guinea');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Eritrea');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Estonia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Eswatini');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Ethiopia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Falkland Islands (Malvinas);');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Faroe Islands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Fiji');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Finland');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('France');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('French Guiana');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('French Polynesia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('French Southern Territories');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Gabon');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Gambia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Georgia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Germany');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Ghana');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Gibraltar');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Greece');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Greenland');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Grenada');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Guadeloupe');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Guam');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Guatemala');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Guernsey');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Guinea');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Guinea-Bissau');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Guyana');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Haiti');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Heard Island and McDonald Islands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Holy See');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Honduras');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Hong Kong');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Hungary');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Iceland');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('India');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Indonesia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Iran (Islamic Republic of);');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Iraq');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Ireland');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Isle of Man');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Israel');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Italy');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Jamaica');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Japan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Jersey');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Jordan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Kazakhstan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Kenya');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Kiribati');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Korea (Democratic Peoples Republic of');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Korea, Republic of');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Kuwait');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Kyrgyzstan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Lao Peoples Democratic Republic');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Latvia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Lebanon');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Lesotho');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Liberia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Libya');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Liechtenstein');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Lithuania');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Luxembourg');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Macao');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Madagascar');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Malawi');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Malaysia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Maldives');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Mali');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Malta');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Marshall Islands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Martinique');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Mauritania');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Mauritius');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Mayotte');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Mexico');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Micronesia (Federated States of)');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Moldova, Republic of');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Monaco');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Mongolia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Montenegro');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Montserrat');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Morocco');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Mozambique');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Myanmar');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Namibia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Nauru');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Nepal');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Netherlands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('New Caledonia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('New Zealand');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Nicaragua');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Niger');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Nigeria');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Niue');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Norfolk Island');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('North Macedonia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Northern Mariana Islands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Norway');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Oman');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Pakistan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Palau');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Palestine, State of');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Panama');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Papua New Guinea');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Paraguay');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Peru');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Philippines');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Pitcairn');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Poland');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Portugal');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Puerto Rico');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Qatar');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Réunion');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Romania');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Russian Federation');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Rwanda');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Saint Barthélemy');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Saint Helena, Ascension and Tristan da Cunha');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Saint Kitts and Nevis');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Saint Lucia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Saint Martin (French part);');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Saint Pierre and Miquelon');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Saint Vincent and the Grenadines');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Samoa');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('San Marino');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Sao Tome and Principe');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Saudi Arabia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Senegal');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Serbia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Seychelles');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Sierra Leone');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Singapore');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Sint Maarten (Dutch part);');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Slovakia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Slovenia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Solomon Islands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Somalia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('South Africa');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('South Georgia and the South Sandwich Islands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('South Sudan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Spain');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Sri Lanka');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Sudan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Suriname');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Svalbard and Jan Mayen');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Sweden');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Switzerland');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Syrian Arab Republic');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Taiwan, Province of China');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Tajikistan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Tanzania, United Republic of');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Thailand');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Timor-Leste');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Togo');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Tokelau');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Tonga');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Trinidad and Tobago');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Tunisia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Turkey');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Turkmenistan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Turks and Caicos Islands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Tuvalu');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Uganda');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Ukraine');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('United Arab Emirates');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('United Kingdom of Great Britain and Northern Ireland');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('United States of America');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('United States Minor Outlying Islands');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Uruguay');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Uzbekistan');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Vanuatu');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Venezuela (Bolivarian Republic of);');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Viet Nam');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Virgin Islands (British);');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Virgin Islands (U.S.);');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Wallis and Futuna');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Western Sahara');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Yemen');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Zambia');
Insert Into [SettlementManagerDb].[dbo].[Countries] (Name) Values ('Zimbabwe');





  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Adamovec','14527',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Andigola','45365',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Antolovec','14657',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Babići','57946',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Kaptol','54777',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Senj','84545',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Požega','43254',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Banja','43242',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Bapska','44978',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Krašić','65474',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Buzet','23576',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Draž','65433',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Pakrac','64533',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Begi','89343',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Ozalj','04530',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Vrbovsko','12345',56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Cerna','32656',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Skrad','75474',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Umag','32572',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Dvor','45236',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Kastav','32426',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Zagreb','98764',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Trnje','64535',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Sesvete','65433',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Klanjec','34223',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Trešnjevka','32423',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Opatija','65243',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Samobor','64321',	56);
  Insert into [SettlementManagerDb].[dbo].[Settlements] (Name, PostalCode, CountryId) Values('Rakitje','10000',	56);